FROM elixir:1.12.1-alpine

MAINTAINER Luca Zulian <contact@lucazulian.it>

# utilities
RUN apk add --no-cache bash

RUN mix local.hex --force && mix local.rebar --force && mix hex.info

ENV ERL_AFLAGS "-kernel shell_history enabled"
